.\" Manpage for git-contributors.
.TH man 8 "3 Mar 2026" "0.1.0" "git-contributors man page"
.SH NAME
git-contributors \- summarize author activity over time
.SH SYNOPSIS
git contributors [OPTIONS]
.SH DESCRIPTION
This utility displays a histogram of commits over time for each author in the current repository.
.SH OPTIONS
See "git-contributors -h" for a list of options.
.SH SEE ALSO
git-log(1)
.SH BUGS
No known bugs.
.SH AUTHOR
basictofu
